- src/ingest-api/app.py
- src/ingest-api/dataset.py
- src/react-app/src/components/ingest/dataset_edit.jsx
@yuanzhou please take a look at this.  I think the changes should be easy to merge.  Let me know and I'll merge them into refactor-zhou
> initial changes for connecting to Joel's endpoint

- docker/docker-compose-ingest-api.localhost.yml
Map the workflow scratch dir into the docker container for localhost
> Change to docker-compose-ingest-api.localhost to map in WORKFLOW_SCRATCH

- docker/docker-compose-ingest-api.prod.yml
Changed location of Airflow install, so we need to update the path to it's static files for nginx.
> Update path to Airflow static files on PROD

- src/ingest-ui/src/App.css
- src/ingest-ui/src/components/uuid/labIdsModal.jsx
- src/ingest-ui/src/components/uuid/tissue_form_components/tissueForm.jsx
Merge 1.11_organ_ui_fixes into 1.11 for the TEST deployment.
> 1.11 organ ui fixes

- src/ingest-ui/src/Collections/Collection.jsx
- src/ingest-ui/src/components/uuid/tissue_form_components/tissueForm.jsx
@boesb I'm merging your tweaks into the `devel` branch for the DEV deployment.
> swapped out  uuid for dataset - replaced properties.uuid with uuid

- docker/ingest-api-dev/nginx/conf.d/zssets.conf
- docker/ingest-api-prod/nginx/conf.d/zssets.conf
- docker/ingest-api-stage/nginx/conf.d/zssets.conf
- docker/ingest-api-test/nginx/conf.d/zssets.conf
Merge http2 support from master
> Http2 support

- src/ingest-api/app.py
Merge into devel for DEV deployment
> Status zhou

- docker/docker-compose-ingest-api.stage.yml
- src/ingest-api/app.py
- src/ingest-api/dataset.py
- src/ingest-ui/src/components/ingest/dataset_edit.jsx
> Globus dir reorg

- src/ingest-ui/src/components/ingest/dataset_edit.jsx
fix the status value after select groups
> fix status

- src/ingest-ui/src/components/ingest/dataset_edit.jsx
> fix submit btn not show

- src/ingest-ui/package-lock.json
- src/ingest-ui/package.json
- src/ingest-ui/src/Collections/Collection.jsx
- src/ingest-ui/src/Collections/Collections.jsx
> Public collections

- src/ingest-api/app.py
- src/ingest-api/dataset.py
Tested on DEV already. Will release to STAGE and PROD.
> added fix for card ingest-ui/issues/303

- src/ingest-ui/src/components/ingest/dataset_edit.jsx
- src/ingest-ui/src/components/uuid/entityList.jsx
- src/ingest-ui/src/components/uuid/tissue_form_components/idSearchModal.jsx
- src/ingest-ui/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/ingest-ui/src/constants.jsx
- src/ingest-ui/src/service/search_api.js
Merge all the recent changes from ui-refactor branch into the ingest-ui (standalone with docker build) version for later deployment.
> UI refactor -> standalone ingest-ui 

- src/src/components/ingest/dataset_edit.jsx
- src/src/components/uuid/donor_form_components/donorForm.jsx
- src/src/components/uuid/entityList.jsx
Changes the wording for the image upload button
Re-Commits some changes done to handle the loading condition
> Image Upload Wording (#388), places & runs Spinner ( #369), Allows human genetic sequences (#391)

- src/src/components/ingest/dataset_edit.jsx
Merges in changes to dataset_edit that validates presence of contains_human_genetic_sequences boolean
> Gene Sequence Validation Fix

- src/src/components/ingest/newDatasetModal.jsx
Recreate PR #434 into test-release branch.
> Opens the Globus URl in the Newly Created Dataset Modal in a new tab
> Globus tab

- src/src/App.js
> Fixes missing idle timer import

- src/src/App.js
- src/src/components/uploads/editUploads.jsx
> Uber uploads

- src/src/components/uuid/donor_form_components/imageUpload.jsx
- src/src/components/uuid/metadataUpload.jsx
Corresponding to the changes made in:
- https://github.com/hubmapconsortium/entity-api/pull/181
- https://github.com/hubmapconsortium/gateway/pull/96
- https://github.com/hubmapconsortium/ingest-api/pull/55
> File upload via ingest-api

- src/package.json
- src/src/App.js
- src/src/components/uploads/createUploads.jsx
- src/src/components/uploads/editUploads.jsx
Addresses Issue #472: 
Addresses Issue #417 
- [x ] Valid
Additionally
> Uploads: Upload Edit View

- src/src/components/uploads/editUploads.jsx
Fix up the Lab Name display in the dataset table for uploads, gets the date into a reasonable format, hides dataset table if not datasets are associated with the upload
> Dataset Table Content for Uploads

- src/src/Datasets/Datasets.jsx
- src/src/components/search/table_constants.jsx
- src/src/components/uploads/editUploads.jsx
Covers Tickets: 
#539 Display HuBMAP ID not UUID on Upload screen 
#540 Add coloring in search list for Uploads in "Reorganized" and "Valid" state 
#542 Change Upload "Validate" button to "Validate & Save" 
#543 Match coloring for Upload states in search list and edit/view screen
> Uploads edits finishing

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
- src/src/components/uuid/result.jsx
- src/src/constants.jsx
- src/src/service/search_api.js
Following PR #545 to be merged into `test-release`
> added wildcard for searching keywords

- src/src/App.js
> Fix logout timer sitch

- src/example.env
- src/src/components/uuid/tissue_form_components/ruiIntegration.jsx
Some modifications are needed to support the RUI 2.0 release. There will be another round of changes in 2 weeks that should improve things further.
> Update to RUI 2.0

- src/src/components/uploads/createUploads.jsx
> Brings validation actions in-line with other creation forms

- src/src/components/uuid/tissue_form_components/tissueForm.jsx
I believe we have the fix in place for the RUI to work. Please turn it back on in the ingest portal for us to finalize testing.
> Turn RUI back on

- src/src/components/uuid/tissue_form_components/ruiIntegration.jsx
I've added some updates that should improve the RUI integration. I'm not a React guy so I _may_ have messed something up, so please take an extra look before merging.
> RUI 2.0 WC Integration Updates

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
Fixes issues with de-rendering & rerendering the Search view when creating new entities
Plus some minor visual tweaks (Fix on card top padding, redundant spinner removed)
> Url Regression Fixes 

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/utils/badgeClasses.jsx
Adds linking to the Datasets listed under an Upload's view, as well as adds the colorful status badges in-line
> Uploads datasets table

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
Add padding to Search card,
Add loading bar to Search view (Solves Double/Zero spinner bug)
Fix wrapping on Login and Content pages,
Fixes some Var definition bugs
Clears out some debugging console logs
> Small UI Adjustments/Fixes 

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
Following the merged PR #612 but for TEST
> Add padding to Search card,

- src/package.json
- src/src/App.js
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Derenders the Linear Progress bar on the Source Search for New entities
> Linear bar fix

- src/src/App.css
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/search/SearchComponent.jsx
patches issue with missing loading bar on searches with slow response time
> Loadbar search patch

- src/src/App.css
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/search/SearchComponent.jsx
provides interface for handling multiple sources for datasets
> Source table view

- src/src/App.css
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/search/SearchComponent.jsx
Reverts hubmapconsortium/ingest-ui#636
> Revert "Loadbar search patch"

- src/src/components/search/SearchComponent.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Following merged PR #644 but for TEST
> fixed issue with failed return from allowable check

- src/src/components/ingest/dataset_edit.jsx
Changes Source label to Source(s) and replaces tooltip content with updated copy
> Changes Source label & tooltip

- src/src/components/uuid/tissue_form_components/tissueForm.jsx
this was showing the incorrect ancestor upon editing the Sample
> fixed source description display for samples

- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Adds a formError entry for Protocol URL DOI Validation, which was previously being cleared by a following successful Protocol URL Validation
Fixes #719
> Protocol URL DOI formError

- src/src/App.js
- src/src/components/ingest/bulk.jsx
- src/src/service/ingest_api.js
Fixes the info capturing for auth info passed through the URL (#734, #737) 
Resolves no-unused warnings & fixes some already-defined warnings
> Auth Capute bugfix & warning cleanup

- src/src/App.js
Fixes link for Bulk Data, re-targets Uploads Modal (#738) 
And closes the topmenu dropdown on Bulk Data menu selection
> Bulk Uploads Target Fix

- src/src/components/ingest/bulk.jsx
Fixes Empty table on bulk tile upload.
Changes Registration button for bulk uploading from "Upload" to "Register"
> UI fixes for Bulk Uploads Table & Reg button

- src/src/components/ingest/bulk.jsx
Properly aligns response data to the preview table once registration's complete
> Cell Alignment for Bulk Preview Table

- src/example.env
- src/public/index.html
- src/src/components/uuid/tissue_form_components/ruiIntegration.jsx
- src/src/constants.jsx
Move to TEST once the changes are verified on DEV via PR #781
> Updates to support CCF RUI v3.0

- src/example.env
- src/public/index.html
- src/src/components/uuid/tissue_form_components/ruiIntegration.jsx
- src/src/constants.jsx
Reverts hubmapconsortium/ingest-ui#785
> Revert "Updates to support CCF RUI v3.0"

- src/example.env
- src/public/index.html
- src/src/components/uuid/tissue_form_components/ruiIntegration.jsx
- src/src/constants.jsx
Reverts hubmapconsortium/ingest-ui#791
> Revert "Revert "Updates to support CCF RUI v3.0""

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
- src/src/service/search_api.js
Applies a list of Columns to the Search Request to only grab the columns the table understands,
Fix for MenuStyle error, as well as unused imports errors
> Search Result Cols

- src/src/components/search/table_constants.jsx
Realigns the Donor Deidentified Name column with the lab_donor_id res…ult column
> Donor Deidentified Name column fix

- src/src/components/ingest/dataset_edit.jsx
Cleans up the Data Type array on submit to endure they're all unique values
Fix for #831
> Makes dataset DT values unique

- src/src/components/ingest/dataset_edit.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
> Unique dt fix

- src/src/components/search/SearchComponent.jsx
Enter Key on the search form Submits the query rather than reloading fixing #856
> Enter Key on the search form Submits the query rather than reloading

- .gitignore
- src/src/App.css
- src/src/App.js
- src/src/assets/App.css
- src/src/components/bulk.jsx
- src/src/components/datasets.jsx
- src/src/components/donors.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/samples.jsx
- src/src/components/uploads.jsx
- src/src/components/uploads/createUploads.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/donor_form_components/donorForm.jsx
- src/test/BulkDonorTest.csv
- src/test/BulkSampleTest.csv
Fixes Button Alignments, adds missing test files, fix some badge colors & Rendering for the Description Form Error for Uploads
> Refactor bugfix

- src/src/App.js
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/donor_form_components/imageUpload.jsx
Fix broken Image Upload & select ESLINT warnings
> Refactor test

- src/src/App.css
- src/src/App.js
- src/src/assets/App.css
- src/src/components/SearchComponent.jsx
- src/src/components/ingest/bulk.jsx
- src/src/components/uploads/createUploads.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/result.jsx
> Bulk and Uploads

- src/src/App.css
- src/src/assets/App.css
> Fix Pagination menu size

- src/src/components/uuid/tissue_form_components/tissueForm.jsx
>  Lock published/public samples for editing

- src/example.env
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Fixes #887 
Replaces legacy Material-ui version of IconButton and Snackbar with newer MUI versions
> Rui button Destyling Fix

- src/example.env
- src/src/components/search/SearchComponent.jsx
> Group search

- src/src/components/uuid/donor_form_components/donorForm.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Was previously only on input changes
Addresses #941
> Applies new protocol url Limiter Validation to On Submit action as well

- src/src/components/uuid/donor_form_components/donorForm.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/utils/validators.jsx
Following merged PR #956 and #969 but for TEST
> Prevents duplicate "doi.org" entries and commas for Protocol.io values

- src/package.json
- src/src/components/ingest/datalist.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
updates globus URL calls to use newer entity api URL
> Globus url

- src/src/App.js
- src/src/Nav.js
- src/src/utils/userInfo.jsx
Following merged PR #973 #976 but for TEST
> Readonly menu

- src/package.json
- src/src/App.css
- src/src/App.js
- src/src/Nav.js
- src/src/components/ingest/datalist.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/samples.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
- src/src/utils/userInfo.jsx
Restyles the MultipleSample Navigation, rendering related samples in scrollable rows/columns, with the current sample highlighted. 
Fixes rendering when navigating to another sample from the multisample navigation.
> Multiple sample navigation

- src/src/App.css
- src/src/components/samples.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Following merged PR #981 for TEST
> Multiple samples

- src/src/App.js
- src/src/Nav.js
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/viewCollectionModal.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/uploads/createUploads.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/donor_form_components/donorForm.jsx
- src/src/components/uuid/entityList.jsx
- src/src/components/uuid/tissue_form_components/idSearchModal.jsx
- src/src/components/uuid/tissue_form_components/idSearchModalMultiSelect.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
- src/src/utils/metadataUpload.jsx
Following merged PR #996 but for TEST
> Services clean

- src/src/components/datasets.jsx
- src/src/components/ingest/dataset_edit.jsx
where Data Providers were not being properly stored from response
> Fixes Data provider Bug

- src/src/components/search/SearchComponent.jsx
- src/src/components/uuid/forms.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/constants.jsx
- src/src/utils/constants.jsx
- src/src/utils/constants_helper.jsx
- src/src/utils/display_subtypes.jsx
Begins the transition away from Sample Types & into Sample Categories
Fixes Data Provider group bug within Sample pages
> Sample categories

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
- src/src/components/search/table_constants.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/constants.jsx
- src/src/service/search_api.js
- src/src/utils/string_helper.jsx
Adjustments To Search Components in both Main Index view and imported Source Selection view
Adjust storage of Sample Type values
Restricts Sample Category to Organ when Source is Donor, Limits to Block/Section/Suspension otherwise
> Sample categories Search Component

- src/src/App.js
- src/src/assets/Documents/example-sample-registrations.tsv
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/uuid/forms.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/utils/validators.jsx
Also Fixes Required highlighting for Sample Category on Sample Creation
Also, also-- just fixed the example bulk upload tsv file -Bill
> Fix New Dataset Registration & DataProvider on Submit/Modal

- src/src/components/ingest/dataset_edit.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/forms.jsx
- src/src/service/entity_api.js
Fix Globus URL handling to handle token based permissions and response wrapping, 
addresses  #1013
> Fix Globus URL

- src/src/components/ingest/dataset_edit.jsx
(when link applies)
addresses #782
> Adds a link to the Dataset view linking back to associated Upload

- src/src/components/ingest/bulk.jsx
Render full value of message on Non-Row-Specific Error during Bulk Sample & Bulk Donor file Upload (#1012)
> Render full Non-Row-Specific Error on Bulk Donor/Sample Upload

- src/src/components/datasets.jsx
- src/src/components/ingest/dataset_edit.jsx
#1019 Datasets that have either Earlier or Later Revisions render a link to navigate at the top of the Viewing form
> Dataset versioning: Navigation

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
End user will receive a message if they haven't been granted read Access to the Hubmap system
> Provides a message for accounts w/o Read access

- src/src/App.js
- src/src/components/search/SearchComponent.jsx
Reverts hubmapconsortium/ingest-ui#1037
> Revert "Provides a message for accounts w/o Read access"

- src/src/components/ingest/dataset_edit.jsx
- src/src/service/ingest_api.js
Adds Service call to determine the Write access sans Status, Properly shows/hides the New Version button, Applies spinner on activity, fixes bug with Direct Ancestor look up in New form mode
> Versioning Interface

- src/src/components/datasets.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/service/ingest_api.js
Following merged PR #1024 but for TEST
> Dataset versioning

- src/src/App.js
- src/src/Nav.js
- src/src/components/bulk.jsx
- src/src/components/datasets.jsx
- src/src/components/donors.jsx
- src/src/components/ingest/bulk.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/samples.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/uploads.jsx
- src/src/components/uploads/createUploads.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/donor_form_components/donorForm.jsx
- src/src/components/uuid/forms.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
- src/src/service/search_api.js
- src/src/utils/string_helper.jsx
> Cleaning comments  and  console  logs

- src/src/App.js
- src/src/Nav.js
- src/src/components/bulk.jsx
- src/src/components/datasets.jsx
- src/src/components/donors.jsx
- src/src/components/ingest/bulk.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/samples.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/uploads.jsx
- src/src/components/uploads/createUploads.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/donor_form_components/donorForm.jsx
- src/src/components/uuid/forms.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
- src/src/service/search_api.js
- src/src/utils/string_helper.jsx
Following merged PR #1045 but for TEST
> Cleaning commentsandconsole

- src/src/components/ingest/publications_edit.jsx
& shorten some input field lengths
> Clear random characters by next version button on publications

- src/src/components/ingest/publications_edit.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/service/search_api.js
Fixes Validation errors for Publication Status where the value wasn't being properly validate (#1079)
>  Fixes Validation errors for Publication Status & Includes in Inclusive search (#1079 & #1078)

- src/src/components/ingest/publications_edit.jsx
- src/src/components/publications.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/search/table_constants.jsx
Fixes the group Modal cancel & form navigation cancel buttons (#1080)
Remove Lab name/ID from Search Columns (#1085)
> Publications

- src/src/components/ingest/publications_edit.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Reference ingestAPI's Allowable Editable States endpoint to verify Has Submit Priv (For Data Admins on Publications marked New) and render the button accordingly (#1055)
> Submit Button for Data Admin

- src/src/components/ingest/dataset_edit.jsx
Remove check against primary assay type for reprocess button, remove errant Save button for select permissions for a published dataset, adapt reprocess feedback to current UI system,
> Reorganize Reprocessing and Submit (oh my 🦁🐯🐻) Buttons 

- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Fix missing Sample Category from ancestor information (& Update label from Sample Type)
> Fix Missing Ancestory Sample Category

- src/src/components/ingest/publications_edit.jsx
Gives the Abstract field in the Publications form more rows & makes required (#1096)
> Publication Abstract Field Changes

- src/src/service/ubkg_api.js
Following merged PR #1109 for TEST
> Adds application context parameters to ubkg api calls

- src/example.env
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/service/ingest_api.js
Hook Slack notifications into Dataset, Publication, and Upload Submission responses via the Ingest service
> Slack Notification on Submission

- src/src/components/ingest/publications_edit.jsx
OMAP DOI field for Publications
> Adds OMAP DOI field for Publications

- src/src/components/search/SearchComponent.jsx
Fixes Column selection on Search when there is one result from a keyword search & the Type option hasn't been selected & the result is a Publication
> Fixes Column selection on Search under specific states

- src/src/components/ingest/publications_edit.jsx
Following merged PR #1123 for TEST
> Tidy OMAP into own Branch

- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
Following merged PR #1147 for TEST
> Dataset status toggle

- src/src/App.js
- src/src/components/collections.jsx
- src/src/components/collections/collections.jsx
- src/src/service/entity_api.js
Faux service for loading test collection data, working t get both New and Edit forms populating properly through newer non-legacy wrapping
> Collections Building

- src/package.json
- src/src/components/collections.jsx
- src/src/components/collections/collections.jsx
- src/src/components/ui/SourcePicker.jsx
- src/src/service/entity_api.js
- src/test/collabTest.csv
Source Selections, CSV Parsing for contributors/contacts, enable new/edit distinction without utilizing legacy Form wrappers
> Collections

- src/src/App.js
- src/src/Nav.js
- src/src/components/collections.jsx
- src/src/components/collections/collections.jsx
- src/test/collabTest.csv
Sort out Table Populations for Datasets based on UUID array, streamline user info to reduce some rerendering issues
> Collections Table Works 

- src/src/Nav.js
Fix permission rendering on main entity nav items
> Fix permission for top nav

- src/src/App.css
- src/src/Nav.js
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Remove the Dropdown menu styling from the Board link & apply similar link styling to the other non-menu link
> Board Link Fixes

- src/package.json
- src/src/components/collections/collections.jsx
Updates FontAwesome Solid Icons to 6.4 & Introduces Bulk Source UUID Management to Source Table for Collections
> FontAwesome & Bulk Source UUID

- src/src/App.js
- src/src/service/ingest_api.js
Reverts hubmapconsortium/ingest-ui#1164
> Revert "Error on new page when no write priv"

- src/src/App.js
- src/src/service/ingest_api.js
Reverts hubmapconsortium/ingest-ui#1182
Will be able to revert-revert the https://github.com/hubmapconsortium/ingest-ui/pull/1181 after merging this PR.
> Revert "Revert "Error on new page when no write priv""

- .gitignore
- src/src/App.js
- src/src/components/collections.jsx
- src/src/components/collections/collections.jsx
- src/src/service/entity_api.js
- src/src/service/ubkg_api.js
- src/src/utils/error_helper.jsx
- src/src/utils/string_helper.jsx
Fix 500 from bulk dataset source bulk uploader, improve capture of UBKG's 500 html error, adds htnl stripper to string utilities
> Collections view

- src/src/components/collections/collections.jsx
Validation feedback for title, description, and sources.
Avoids including Blank Contacts & Contributors
> Validations / Blank Trims

- src/src/components/ingest/bulk.jsx
> Fix to capture error on response to initial Bulk Donor file upload

- src/src/service/search_api.js
Limits searches that begin with HBM to an exact-match single entity response
> Hubmap ID Limited Search Results

- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Following merged PR #1212 for TEST
> Removes the "Add A Metadata File" button from Sample forms

- src/src/components/ingest/publications_edit.jsx
Enable Revision Creation/management for Publications (Addresses #1198)
> Pub version

- src/src/components/collections/collections.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/utils/display_subtypes.jsx
Defaults Bulk Dataset UUID/HID Input to 2 line & allows for resizing (RE #1216)
Also fixes crash when Dataset Display Type isn't found; Replaces with "N/A"  (Occurs when using old test data with improper Data Type information, but will allow any live errors to fail gracefully)
Also includes fixes for #1215 Better Feedback on Bulk Dataset Entry Error Responses
> Multiline Bulk Dataset Input, Bulk Dataset Error Feedback

- src/src/components/ingest/publications_edit.jsx
Following merged PR #1217 for TEST
> Enable Revision Creation/management for Publications

- src/src/components/collections/collections.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/utils/display_subtypes.jsx
Following merged PR #1223 for TEST
> Collection dataset input

- src/src/service/search_api.js
Following merged PR #1234 for TEST
> Hid search

- src/package.json
- src/src/components/ingest/bulk.jsx
- src/test/BulkSampleTest.csv
Adds a button to download the table of results once the Bulk Registration completes successfully as a CSV file
> Download Results on Bulk Success

- src/package.json
- src/src/components/ingest/bulk.jsx
- src/test/BulkSampleTest.csv
Following merged PR #1244 for TEST
> Download bulk

- src/cypress.config.js
- src/cypress.env.json
- src/src/App.js
- src/src/components/collections/collections.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/search/table_constants.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/constants.jsx
- src/src/service/ingest_api.js
- src/src/service/search_api.js
- src/src/service/ubkg_api.js
Enables Collections in the Search Component
Updates the Search Component to accept a Whitelist and a Blacklist for available Entity Types
Fixes table overflows on the Collections view
> Collection reveal

- src/src/App.css
- src/src/App.js
- src/src/assets/App.css
- src/src/components/bulk.jsx
- src/src/components/ingest/bulk.jsx
Catches Gateway Timeout / 504 Errors on Bulk submissions
> Bulk debugging

- src/src/constants.jsx
- src/src/service/search_api.js
Adjusts Search to refer to a Collections Dataset fields for Group UUID information rather than the Collection itself
> Collection Groups Search by Dataset

- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
Following merged PR #1292 for TEST
> Contains pii fix

- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
only display the dropdown menu for new dataset creation, and for existing datasets, disallow the edit to this type field, just display the existing value without using dropdown menu
for publication creation, remove dataset_type == 'Publication' 
comment out various deprecated assay rendering functions
> Soft assay conversion

- src/src/components/collections/collections.jsx
Following merged PR #1312 for TEST
> Fix blank title & description when a Collection has no sources

- src/src/components/ingest/dataset_edit.jsx
Following merged PR #1320 for TEST
>  Restore subtype label to previously assigned sources on datasets

- src/src/components/ingest/dataset_edit.jsx
exclusively available on Creation only now
> Remove Dataset Type From edit/update calls for datasets

- .gitignore
- docker/docker-compose.yml
- src/example.env
- src/package.json
- src/public/assets/liveBanner.example.js
- src/public/index.html
- src/src/App.js
- src/src/components/search/SearchComponent.jsx
- src/src/components/search/searchTable.jsx
- src/src/utils/string_helper.jsx
Enable Live Banner that's applied through Env Vars, 
also Fixes missing Portal Title on Search Views
> Enable Live Banner that's applied through Env Vars, 

- .gitignore
- docker/docker-compose.yml
- src/example.env
- src/package.json
- src/public/assets/liveBanner.example.js
- src/public/index.html
- src/src/App.js
- src/src/components/search/SearchComponent.jsx
- src/src/components/search/searchTable.jsx
- src/src/utils/string_helper.jsx
Following merged PR #1331 for TEST
> Live banner

- src/src/components/ingest/dataset_edit.jsx
Specifically on Multi-Assay Split & Central Process datasets 
(#1318)
>  Disallow editing direct ancestors Some Datasets

- src/src/components/collections.jsx
- src/src/components/datasets.jsx
- src/src/components/donors.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/metadata.jsx
- src/src/components/publications.jsx
- src/src/components/samples.jsx
- src/src/components/uploads.jsx
- src/src/service/ingest_api.js
Redirects if the user loads an entity under the wrong type in the URL
> Entity redirect

- src/src/components/search/searchTable.jsx
Fixes visibility of Search Table columns that were previously hidden with the older datagrid
> Fixes visibility of Search Table columns

- src/src/components/samples.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/entity_api.js
Fix RUI Button Rendering on Nested Samples
> Sample r UI organ

- src/src/App.js
- src/src/Nav.js
Following merged PR #1348 #1357 for TEST
> Update logout to properly interface with globus

- src/src/components/search/searchTable.jsx
- src/src/components/uploads/editUploads.jsx
Following merged PR #1360 for TEST
> Upload helpers

- src/src/App.css
- src/src/assets/App.css
- src/src/utils/badgeClasses.jsx
Following merged PR #1352 for TEST
> Adds Incomplete status badge support

- src/src/components/collections.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/uploads/editUploads.jsx
Also fixes crash on new collection form 
And Title fix for new form pages using Source selector
> Uploads badge upgrade

- .github/workflows/node.js.yml
- docker/ingest-ui/Dockerfile
- src/package.json
- src/src/components/datasets.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/publications.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/search/table_constants.jsx
Hides Multiple Revision interfaces, 
Includes the Search Column Menus and nodejs 20 upgrade
> Multi version hide & Main Backport

- src/src/App.css
- src/src/assets/App.css
- src/src/components/collections.jsx
- src/src/components/collections/collections.jsx
- src/src/components/search/table_constants.jsx
Updates the collections UI to utilize a datagrid for the Associated Entity field (Formerly labeled Source)
> Collections UI Associated Entities

- src/src/components/datasets.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/publications.jsx
Following merged PR #1388 for TEST
> Remove versioning navigation & creation from Datasets & Publications

- src/src/App.js
- src/src/components/collections/collections.jsx
- src/src/components/search/table_constants.jsx
Fix lingering references to Sources, 
Include Fix for HuBMAP ID Column Head,
Submission ID column re-appearing with Multiple datasets selected
Fix the Table header that was hiding the "No Result" text on empty table
> Collections UI

- src/src/App.js
- src/src/components/metadata.jsx
- src/src/utils/error_helper.jsx
Following merged PR #1418 #1421 #1423 for TEST
> Bulk validation updates

- src/src/components/uploads/editUploads.jsx
Following merged PR #1443 #1445 for TEST
> Make fields editable in Incomplete status - #1424

- src/public/index.html
- src/src/components/uploads/editUploads.jsx
- src/src/constants.jsx
Adds URLs and organ code mapping for left and right Tonsils
Updates resource for RUI interface to cdn.humanatlas.io
> Updates to RUI including Tonsil Support

- src/src/App.js
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
Update render and validations for Contributors for collections and EPICollections, as well as add new error feedback box for each, fix tabbing for epicollections fix typo, fix logout bug and timer check
> Updates to Contributors for collections and EPICollections + logout fix

- src/public/index.html
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/constants.jsx
> BulkUUIDids

- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
Following merged PR #1450 for TEST
> Fix for Bulk adding datasets to collections/EPICollections (#1437)

- src/src/App.js
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/uuid/tissue_form_components/ruiIntegration.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/ubkg_api.js
- src/src/utils/display_subtypes.jsx
- src/src/utils/ruiIntegration.jsx
Moves these values into localStorage
> Upgrade utilization of UBKG Organs and DatasetTypes

- src/src/App.js
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/ingest/dataset_edit.jsx
Fixes the rendering for the Submit modal on datasets
> Submit fix

- src/src/components/ingest/dataset_edit.jsx
Following merged PR #1454 for TEST
> fix rendering of submit modal for submitting datasets

- src/src/App.js
Adds visual feedback on a failure with either UBKGs organs endpoint or UBKGs Data Type endpoint, and informs user if stored data is being used. If no stored information is available, provides Help desk email
> Ubkg cache

- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/uuid/groupModal.jsx
also fix rendering of post-group selection
> Update collection Creators to Contributors, 

- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/uuid/groupModal.jsx
Following merged PR #1459 for TEST
> Collection contributors

- src/src/App.js
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/uuid/tissue_form_components/ruiIntegration.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/ubkg_api.js
- src/src/utils/display_subtypes.jsx
- src/src/utils/ruiIntegration.jsx
Reverts hubmapconsortium/ingest-ui#1456
> Revert "Ubkg cache"

- src/src/App.js
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
Re enables the Contacts field internally on Collections and EPICollections (
> Collection & EPICollection contacts

- src/src/components/ingest/bulk.jsx
- src/src/components/metadata.jsx
Following merged PR #1473 for TEST
> Update Bulk Example to point to the Main github branch

- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
Following merged PR #1475 for TEST
> Collection contacts

- src/src/components/uploads/editUploads.jsx
Following merged PR #1517 for TEST
> Input Value Update fix for Task Assignment on Uploads

- src/src/components/ingest/dataset_edit.jsx
- src/src/service/ingest_api.js
Zhou edited: Following merged PR #1527 #1528 for TEST
> Submit for testing Button

- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/service/ingest_api.js
Provide Feedback to user on Invalid TSV Upload for Contributors and Block Submit on invalid file
> Contributor cedar validation

- src/src/components/ingest/dataset_edit.jsx
- src/src/components/uuid/result.jsx
- src/src/service/ingest_api.js
Fix Rendered button mismatch on successful donor registration
> Donor button fix

- src/package.json
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/uuid/result.jsx
- src/src/service/ingest_api.js
Merges main back in (Which includes all of the recent contributors changes)
Updates the Reset interface rendering to show for all Non Published Publications
> Merge Main & Update Status Validation for Reset Functionality rendering

- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Following merged PR #1543 #1547 for TEST
> Lock sample values

- src/src/components/ingest/publications_edit.jsx
- src/src/components/search/table_constants.jsx
(#1393 ) Also Address #1535 and Removes the Duplicated created_by_user_email field for Publication Column Definitions
> Remove Submission ID From Publication Source Table

- src/src/components/ingest/publications_edit.jsx
- src/src/components/search/table_constants.jsx
Following merged PR #1546 for TEST
> Publication sub

- src/src/Nav.js
- src/src/components/metadata.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
- src/src/utils/error_helper.jsx
New Uploader to handle interfacing with the new Ingest API endpoint
> New Bulk Meta UI

- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
Ensure Ordering of Responses from Contributors errors on Collections/EPICollections, improve single-message error capture
> Ensure Ordering of  Error Responses

- src/src/components/search/table_constants.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
Addresses:
UI for new samples always claims DOI is invalid until Submission
[#1389](https://github.com/hubmapconsortium/ingest-ui/issues/1389)
Collections group in search results table
[#1400](https://github.com/hubmapconsortium/ingest-ui/issues/1400) and
> Quick fixes

- .gitignore
- src/.eslintrc.js
- src/.gitignore
- src/package.json
- src/src/.eslintrc.examplejs
- src/src/App.js
- src/src/Nav.js
- src/src/components/newDonor.jsx
- src/src/components/uuid/result.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
Replaces the donor form with a new upgraded & streamlined version, 
Makes changes to the App and Nav to reduce re-renders and shift more weight from useEffects to localStorage, hooks the Entity API Service and Ingest API Service into the localStorage for Tokens
> Donor upgrade + App/Nav/Component Supporting Upgrades 

- src/src/App.js
- src/src/Nav.js
- src/src/components/newDonor.jsx
- src/src/components/ui/HIPPA.jsx
Fix Hippa Modal Loading state issue, fix error in console regarding invalid nesting of modal content, Improve Error Validation on the new Donor form & include Formatting validations as used in the Sample form, improve hook-in to input to render form errors, fix issue with the userGroups content setting that could store breaking data,
> Build Error Fixes + Donor form & userGroup handling improvements

- src/.gitignore
- src/src/.eslintrc.js
- src/src/App.js
- src/src/Nav.js
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/search/table_constants.jsx
- src/src/utils/validators.jsx
Also includes new eslintrc, streamlining to validating/storing dataset types
> Fix Docker Build Errors 

- .gitignore
- src/.eslintrc.js
- src/.gitignore
- src/package.json
- src/public/index.html
- src/src/.eslintrc.examplejs
- src/src/.eslintrc.js
- src/src/App.css
- src/src/App.js
- src/src/Nav.js
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/newDonor.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/search/table_constants.jsx
- src/src/components/ui/HIPPA.jsx
- src/src/components/ui/result.jsx
- src/src/components/uuid/result.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/entity_api.js
- src/src/service/ingest_api.js
- src/src/utils/validators.jsx
Following merged PR #1580 #1582 #1583 #1584 for TEST
> Donor upgrade

- src/package.json
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/search/table_constants.jsx
- src/src/components/uuid/donor_form_components/donorForm.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/search_api.js
- src/src/utils/string_helper.jsx
- src/src/utils/validators.jsx
Addresses [#1462](https://github.com/hubmapconsortium/ingest-ui/issues/1462) for issues listed on the [code scanning](https://github.com/hubmapconsortium/ingest-ui/security/code-scanning) page
> Security flag fixes

- src/src/components/newSample.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/uuid/tissue_form_components/multipleListModal.jsx
- src/src/utils/ruiIntegration.jsx
Adds Datasets, Uploads, & Publications to the Sample Source Selector Search Blacklist
marks Source ID as Required, 
Impliment "Sub-title" customization (The regular one was clashing with the applied blacklist on the search interface)
fix various typos, 
remove needless check on Lab Id / Multiples conflict, 
update Multiples label, 
Update content fill on select Multiples views,
Change order of fields to place Generate Multiple Samples below Details
> Sample upgrade

- src/src/components/newDonor.jsx
- src/src/components/newSample.jsx
- src/src/components/newUpload.jsx
- src/src/components/ui/formParts.jsx
Move the setting of the Document Title into the formParts FormHeadercomponent, 
move the status bar chip down into the subhead area, 
fix valueSetting of the DatePicker, 
add NaN validation to anticipated_dataset_countfield, 
update validation error rendering to provide per-field feedback by line and include non-required valdiation errors,
move the entityData.validation_message into a collapsable frame
> Uploads Feedback & Polish

- src/src/components/newUpload.jsx
- src/src/components/search/table_constants.jsx
Fix Row/Cell click action and Button Default action on Dataset table in the Upload form, reduce excess bloat on table rows
> Upload Feedback

- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/newUpload.jsx
- src/src/service/ingest_api.js
Fixes for Slack Notify Service on Submit (Uploads, Datasets, and Publications)
Clearing out Logging
> Uploads Upgrade: Slack Notify & Console

- src/src/components/newUpload.jsx
- src/src/components/ui/formParts.jsx
Per Request:
- Fix the button stickyness (match actively processing button state with form-processing/Disabled button states)
- Manual Invalid Date Error Polish (Reinforce Validation Checking on Manually-entered Dates, improve Error-State Rendering for anticipated_complete_upload_month field)
Also:
- Adjust font weight in chip 
- Adjust Default/Collapsed Height of the Validation Message detail
> Uploads Form Feedback

- src/src/components/newUpload.jsx
brings Dialoge into Sync with others using full color titles
fixes Typo preventing submitting from submitting
> Upload submit: fix typo & dialog title styling

- src/src/components/newUpload.jsx
- src/src/components/ui/formParts.jsx
Following merged PR #1632 #1634 #1635 #1637 #1638 #1638 for TEST
> Upload submit

- src/src/components/ingest/dataset_edit.jsx
Following merged PR #1649 for TEST
> Allows ADMIN users to Save on Datasets with the QA status

- src/src/components/newPublication.jsx
- src/src/components/ui/bulkSelector.jsx
- src/src/components/ui/formParts.jsx
Extracts the Bulk Source Manager to its own component, 
Fixes missed error responses on form actions,
Improves handling of Bulk String (Comma spacing & Trailing no longer an issue),
Returns the Purple NEW badge to new forms (with corresponding icon), 
Memo-ifies form structure for improved loading & stability, 
adds No Data row to empty source table
> Publications Polish

- src/src/components/newPublication.jsx
- src/src/components/ui/bulkSelector.jsx
> Validation Highlight fixes

- src/package-lock.json
- src/package.json
Removes ESLint & runs npx update-browserslist-db@latest to update caniuse for easier debugging of build script
> CLears Logs for Build Debugging

- src/src/components/ui/result.jsx
Add Clarifying text to tooltip post Donor Creation, moved toolip to below the button
> Success tooltop

- src/src/App.js
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/newUpload.jsx
- src/src/components/ui/formParts.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/service/ingest_api.js
- src/src/utils/error_helper.jsx
- src/src/utils/revertModal.jsx
Following merged PR #1706 for TEST
> Validation placeholder

- src/src/components/newPublication.jsx
- src/src/components/ui/bulkSelector.jsx
- src/src/components/ui/formParts.jsx
Delete icon doesn't work on the New Publication creation source selector And Warning Modal Stuck Open On View
[#1705](https://github.com/hubmapconsortium/ingest-ui/issues/1705)
> Fix Error on Deleting Source in New Publication

- src/src/components/datasets.jsx
- src/src/components/newSample.jsx
- src/src/components/publications.jsx
- src/src/components/ui/icons.jsx
- src/src/components/ui/result.jsx
- src/src/components/uuid/forms.jsx
- src/src/components/uuid/result.jsx
Following merged PR #1708 #1711 #1715 for TEST
> Concurrence

- src/src/components/newPublication.jsx
- src/src/components/ui/bulkSelector.jsx
- src/src/components/ui/formParts.jsx
Following merged PR #1713 for TEST
> Publication bulkfix

- src/src/App.js
- src/src/components/newSample.jsx
- src/src/components/ui/formParts.jsx
Fixes NODE_ENV check for debug render vs user RUI Rejection render, 
Includes SpeedDial tool for quickly sharing prefilled forms via URL extraction
> RUI Rejection Render

- src/src/components/newDataset.jsx
- src/src/components/ui/bulkSelector.jsx
- src/src/components/ui/formParts.jsx
Fix Casing issue for Search Blacklist
> Fix Casing issue for Search Blacklist
