hubmapconsortium/ingest-ui

- src/ingest-api/app.py
- src/ingest-api/dataset.py
@jswelling this PR includes:
- added new endpoint and functionalities to handle the creation of derived dataset from a parent dataset.
- the endpoint is a POST to the ingest-api: /datasets/derived
The input requires a globus nexus token (for group access) and the JSON example:
````
{
"source_dataset_uuid":"e517ce652d3c4f22ace7f21fd64208ac",
"derived_dataset_name":"Test derived dataset 1",
"derived_dataset_entity_type":"Dataset"
}
````
and the response JSON:
````
{
"derived_dataset_uuid": "2ecc257c3fd1875be08a12ff654f1264",
"group_display_name": "IEC Testing Group",
"group_uuid": "5bd084c8-edc2-11e8-802f-0e368f3075e8"
}
````
> Ingest pipeline integration - creating derived dataset - zhou

- src/ingest-api/dataset.py
- src/ingest-api/instance/app.cfg.example
Mods to dataset.py to allow setting of default ingest-pipeline DAG from the .cfg file.
> Mods to support choice of default ingest pipeline from config

- src/ingest-api/app.py
- src/ingest-api/dataset.py
@jswelling this is a fix to the data type from the json input. 
The updated input json looks like:
````
{
"source_dataset_uuid":"e517ce652d3c4f22ace7f21fd64208ac",
"derived_dataset_name":"Test derived dataset 1",
"derived_dataset_types":["QX11", "xxx"]
}
````
Note: the `"derived_dataset_types"` is a json array now. You can pass in only one item if not multiple data types.
Output JSON stays no change:
````
{
"derived_dataset_uuid": "2ecc257c3fd1875be08a12ff654f1264",
"group_display_name": "IEC Testing Group",
"group_uuid": "5bd084c8-edc2-11e8-802f-0e368f3075e8"
}
````
After merging this PR, on your localhost, you'll need to stop and remove the ingest-api container, also delete the ingest-api image. Because some code changes are made in the commons repo, which is a python dependency to the …
> Ingest pipeline integration fix

- docker/docker-compose-ingest-api.dev.yml
- docker/docker-compose-ingest-api.prod.yml
- docker/docker-compose-ingest-api.test.yml
- docker/docker-compose-ingest-ui.dev.yml
- docker/docker-compose-ingest-ui.prod.yml
- docker/docker-compose-ingest-ui.test.yml
- docker/ingest-api-dev/Dockerfile
- docker/ingest-api-dev/entrypoint.sh
- docker/ingest-api-prod/Dockerfile
- docker/ingest-api-prod/entrypoint.sh
- docker/ingest-api-prod/nginx.conf
- docker/ingest-api-prod/nginx/conf.d/ingest-api.conf
- docker/ingest-api-test/Dockerfile
- docker/ingest-api-test/entrypoint.sh
- docker/ingest-api-test/nginx.conf
- docker/ingest-api-test/nginx/conf.d/ingest-api.conf
- docker/ingest-ui/Dockerfile
- docker/ingest-ui/entrypoint.sh
- docker/ingest-ui/ingest-ui.conf
- docker/ingest-ui/nginx.conf
This PR:
- de-elevates root to hubmap user (mapped with the host UID and GID) for running nginx, uwsgi and docker processes
- the docker-compose takes UID and GID as new environment variables for passing host user info to docker container
- internal ports changes to allow nginx run as non-root process
> Docker non root

- docker/docker-compose-ingest-api.test.yml
We changed the directory where Airflow is installed, so we need to update the path to the Airflow static files for nginx.
> Update Airflow TEST static path

- src/ingest-ui/src/components/uuid/tissue_form_components/ruiIntegration.jsx
This should remove the need for the assets folder on dev and will use the assets stored in the CDN. This will eliminate the reference organ data mismatch identified earlier.
> Use the baseHref RUI option

- src/ingest-ui/src/components/uuid/tissue_form_components/ruiIntegration.jsx
I can't test this locally, but I believe this will give us the kind of screen real estate that the RUI needs in order to be effective.
> Give RUI more screen real estate

- src/ingest-ui/example.env
This PR changes the example.env to use the official 1.x release of the RUI. You'll need to update the actual .env in your infrastructure.
> Switch RUI from staging releases to official 1.x releases

- src/src/App.js
- src/src/components/uploads/createUploads.jsx
> Uber uploads

- src/public/index.html
- src/src/constants.jsx
Added some styling tweaks (needed styles pulled from the same BASE_URL as RUI 2.0. Currently hardcoded in index.html, but maybe it can be pulled from `process.env.REACT_APP_RUI_BASE_URL` somehow (not a React guy so I'm just doing what I can)? 
Also added a few more organs that RUI 2.0 supports. There are actually more, but we are waiting for the IRIs to make their way to this project (@shirey).
> More RUI 2.0 tweaks

- src/src/components/uploads/editUploads.jsx
Unhides the Uploads menu item from the top navbar,
Increases the Max Height for the Associated Dataset Table
> Unhide Uploads

- src/src/components/search/SearchComponent.jsx
- src/src/components/uploads/editUploads.jsx
Adds Helper text for Save & Submit buttons when Upload is Writeable
Fixes call to ingest API's submit
Decouples Save & Submit button behavior, each should spin without spinning the other (consider still disabling others though)
> Uploads Adjustments

- src/src/App.js
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/search/SearchComponent.jsx
- src/src/components/uploads/editUploads.jsx
- src/src/components/uuid/tissue_form_components/tissueForm.jsx
- src/src/service/entity_api.js
Attempting to have the Search table re-load after saving an entity, so it'll contain the newly updated data
Removes the lingering Upload Edit form from under the Search Component post-save
> Uploads unhide

- src/src/components/uuid/tissue_form_components/ruiIntegration.jsx
Somehow user is being passed as null to the rui integration code. I put in a guard to protect against it and not fail, but ultimately, user _should_ be being passed in here.
> Handle incorrectly populated user prop

- src/src/service/search_api.js
Sorts Search Results ASC instead of DESC, so the Oldest appears First instead of Last. Fixes #813
> Small PR for Search Result Order

- src/src/components/ingest/dataset_edit.jsx
AWS at times responds with 202 Accepted in place of 200 OK, which was getting caught in Legacy Error checks
> Adapts to change in response Status from 200 to 202

- src/src/components/uploads/editUploads.jsx
Remove the Validate button for user roles data_curator & data_group_editor ([#1193](https://github.com/hubmapconsortium/ingest-ui/issues/1193))
> Removes Upload Validation for Currators & Group Editors

- src/src/service/search_api.js
Fix Hubmap ID search to utilize only the hubmapid.keyword for es, avoiding search results based on the values of an entity's source
(#1229)
> Fix Hubmap ID search

- src/example.env
Updates DATA_ADMIN and DATA_CURATOR to REACT_APP_DATA_ADMIN and REACT_APP_DATA_CURATOR so they're not dropped by react-scripts
> Env var name fix

- src/src/components/search/searchTable.jsx
- src/src/components/uploads/editUploads.jsx
Selectively render helper text on data Uploads based on availability of actions, fix Save button rendering when upload isn't actually writable
> Selectively render helper text on data Uploads based on availablility

- src/src/App.js
- src/src/components/collections.jsx
- src/src/components/collections/collections.jsx
- src/src/components/search/searchTable.jsx
- src/src/components/search/table_constants.jsx
Updates to Ownership Group assignment/selection
Replaces Delineated Contacts/contributors table with a combined table using a column for Contact status rendering
Various fixes to table columns and values rendering
> Collections UI

- src/src/components/uploads/editUploads.jsx
Change log:
1. Allow Save button to be visible on Incomplete status
Needs admin testing.
> Add incomplete status to list to render save button - #1424

- src/src/App.css
- src/src/App.js
- src/src/Nav.js
- src/src/assets/App.css
re-apply localhost detection for timer rendering, fix issue with logout button, clarify logout request status with button, clean up a few tabs & comments (tracking with #1464 )
> Fix for logout button and process

- src/src/App.js
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
- src/src/components/datasets.jsx
- src/src/components/ingest/dataset_edit.jsx
- src/src/components/ingest/publications_edit.jsx
- src/src/components/publications.jsx
- src/src/service/search_api.js
- src/src/service/ubkg_api.js
- src/src/utils/display_subtypes.jsx
Update Dataset Type URL for UBKG Service (#1440)
Update Dataset form, Publications form, Display subtype utility, Collections & EPICollections handling of Display Subtypes
Remove unused search_api_get_assay_list from search api service
> Dataset types url

- src/src/App.css
- src/src/assets/App.css
- src/src/components/collections/collections.jsx
- src/src/components/collections/epicollections.jsx
Admin need access to the Creation forms for Collections and EPICollections per slack/@yuanzhou 
this does not account for any top menu link access for Admins who dont already have the menu through their Data Provider access, or any changes needed to allow edit access for previously denied creation of other entities, [(outlined here)](https://github.com/hubmapconsortium/ingest-ui/issues/872), nor updating that table, nor the creation/documentation of new Admin/Provider Combined Account. 
Now includes repositioned doi link
> Enable Creation of Collections/EPICollections for Admin users

- src/src/App.css
- src/src/App.js
- src/src/Nav.js
- src/src/assets/App.css
- src/src/components/metadata.jsx
- src/src/components/ui/dialog.jsx
Following merged PR #1502 for TEST
> capture of network failures

- src/src/components/ingest/publications_edit.jsx
Fix Missing Publication Status Revert Function and Collapsing update button (#1522 )
> Fix Missing Publication Status Revert Function & button

- src/src/components/newDonor.jsx
- src/src/components/newSample.jsx
- src/src/components/newUpload.jsx
- src/src/components/ui/formParts.jsx
Fix issue with readgroup-specific user accounts without DataProvider experiencing a crash on loading entity forms.
(addresses #1688)
Also Fixes Undefined window titles on new forms
> Read Only User UUID Crash Fix

- src/src/components/datasets.jsx
- src/src/components/newSample.jsx
- src/src/components/publications.jsx
- src/src/components/ui/result.jsx
- src/src/components/uuid/forms.jsx
- src/src/components/uuid/result.jsx
Re-Enables the Create Organ from Donor` and `Create Sample from Organ` buttons post-registration for Donors and Samples
Adds small detail in the disables RUI message if required Donor Metadata is missing (sex)
Allows Sample form fields to be populated by URL params
> Concurrent Sample Reg Flow

- src/.gitignore
- src/src/components/newSample.jsx
Fix flipped truthy check on organ status, Adjust Rendering of feedback text further & simplify responses, remove nonprod checks for the Debugging tooltip, but attached it to the Alert box itself and modified it to only activate when hovering with Shift or on clicking it. Nix some React logs regarding field input properties, Add Cypress Screenshots to gitignore
> RUI wrapup

- src/src/components/newDataset.jsx
Also replaces UUID Selection for ingest_api_validate_entity && ingest_api_dataset_submit (This just ensures it's only given UUIDs to digest)
> Switch url uuid handling with entityData at Processing action
